### PR TITLE
percent decode form encoded data

### LINKED ISSUE #230: validation failing emails via POST
```
{
    "message": "Validating Email failed for input 'tanner%40qutheory.io'",
    "error": true
}
```

Looks like we need to do percent decoding before we analyze the input.

### PR DESCRIPTION
**Pull request by tannernelson**
Fixes #230

### CODE REVIEW

File: Sources/Vapor/Request/Request.swift [hunk 1]
```diff
@@ -72,7 +72,8 @@ extension Request {
             let token = pair.split(separator: "=", maxSplits: 1)
             if token.count == 2 {
                 let key = String(validatingUTF8: token[0]) ?? ""
```
Comment (LoganWright) [inline Sources/Vapor/Request/Request.swift]: Does key need any percent encoding work as well?
